### ISSUE TITLE
Clarify Jentrata partnership setup

### ISSUE THREAD

**Issue by telstrajhinjer** [jentrata/jentrata-msh#51]
@aaronwalker I have configured a partnership id and its transform endpoint. But instead of sending ebxml to transform endpoint its sending acknowledgement to transform endpoint.

**Comment by telstrajhinjer** [comment]
hk.hku.cecid.piazza.commons.net.ConnectionException: Unable to send HTTP SOAP request
	by java.net.SocketTimeoutException: Read timed out

**Comment by aaronwalker** [comment]
@telstrajhinjer Is your expectation that Jentrata will call an SOAP web service on receipt of a message from a partner? If so that is not what Jentrata will do. Jentrata will generate a ebXML ack and send it to the url you have configured for your partner. You can then access the payload using the soap interfaces. You need to poll for these messages. Unless your  using the camel integration it can then push the message to another system JMS/File etc.

When you have a loopback partnership agreement the URL you configure should be Jentrata itself. You need to set the transport url to `http://localhost:8080/jentrata/httpd/ebms/inbound` This basically triggers jentrata to send the message to itself then generate an ebAck and send that to itself hence loopback 😄. This allows you test without the need for another gateway. 

I think you have not quite understood what Jentrata and overall ebXML handshake between trading partners entails. With Jentrata you can exchange message with trading partners using ebXML. This entails digitally signing and verifying those messages and providing acknowledgment of receipt of those messages (ebACK) The transport url you configure in the partnership is that of your partners gateway not an internal system. To integrate Jentrata with internal systems that where the Web services I already mentioned  come in to play. This requires polling to get the payload into internal system. If you want them to be pushed you need to use the camel integration provided.
